-- +goose Up
-- 00021_act_delegations.sql (ENT-230, §26.3, §8, §20.1)
--
-- Acting for a person: how an agent reads and writes as the human who asked,
-- without ever holding that human's token.
--
-- THE PROBLEM THIS SOLVES, STATED AS THE ATTACK IT PREVENTS
--
-- The dashboard rail is an agent acting for a signed-in user, so its tools have
-- to bind to that person's scope, tenancy and audit trail. Intelligence holds
-- no user token and never will (§1.6): it authenticates as a machine principal
-- through client credentials, and a machine principal has no membership
-- anywhere.
--
-- The lazy version of this is a request field: the machine names the person it
-- is acting for, and core-api believes it. That is authority laundering. Any
-- component holding `internal:act-on-behalf` could then act as anybody, in any
-- organisation, and the audit trail would record the lie in the customer's own
-- compliance record.
--
-- So the person's identity is not asserted, it is presented. Core-api mints a
-- delegation while it is serving that person's own request, hands the agent an
-- opaque credential, and the agent can only ever hand it back. What the agent
-- may do is then whatever the person may do, decided by the same memberships,
-- policies and role checks that decide it at the keyboard.
--
-- WHY THE ANTI-LAUNDERING RULE IS A POLICY AND NOT A GO CHECK
--
-- The with-check on `act_delegations_mint` pins every row to the two tenancy
-- GUCs: `kindlast_app` can insert a delegation only for the person whose
-- session is open, in the organisation they are acting in, and only while they
-- are still a member of it. A minting handler that read the user id out of a
-- request would be refused by Postgres rather than obeyed.
--
-- That is the AGENTS.md test working as written: this must hold no matter who
-- writes, so it is a constraint rather than a decision. The decisions around it
-- (how long a delegation lives, whether this caller may mint one at all, what
-- happens when it will not resolve) are all in Go.
--
-- WHY REDEMPTION IS SECURITY DEFINER, WHICH IS NOT A PRECEDENT FOR MORE PLPGSQL
--
-- Resolution runs with NO tenancy GUCs set, because resolving the delegation is
-- what decides whose session this becomes. Every policy in the schema reads
-- those GUCs, so RLS structurally cannot express this check: the caller has not
-- yet been identified. That is the same argument `redeem_capability_token`
-- rests on (00015), and it is the narrow exception §-what-goes-in-the-database
-- allows rather than a licence to add the next function.
--
-- The function is deliberately mechanical. It finds a live row and returns who
-- it names. It does not check membership, because membership is checked in Go
-- immediately afterwards, by the same query `BeginTenant` already runs under
-- the `memberships` select policy. Two consequences worth stating: a person who
-- lost their membership mid-run is refused on their agent's next tool call, and
-- the check that refuses them is the one the whole system already trusts.
--
-- ONE PRIMITIVE, AND THE SECOND CONSUMER IS NOT BUILT HERE
--
-- ENT-230 also carries §8's one-tap approve link, which is the same delegation
-- with a different redemption path: single use, bound to one finding, redeemed
-- through an interstitial in `web`. `single_use` is here because it is the
-- difference between the two consumers and it is two lines; the finding
-- binding, the route and the interstitial are not, and guessing their shape
-- would be inventing a design nobody has reviewed. What this migration commits
-- to is that the second consumer is a redemption path plus a column, not a
-- second table of bearer credentials.
--
-- WHY NOT WIDEN `capability_tokens` (00015), WHICH THE ISSUE'S WORDING SUGGESTS
--
-- Because that table's redemption function PERFORMS the act inside redemption:
-- `redeem_capability_token` writes the notification preferences itself. A
-- delegation performs nothing. It answers "who is this" and hands the answer to
-- the ordinary request path, which is the property that makes an agent's write
-- indistinguishable from the person's own except in who is named beside it.
-- Its rows are also minted by a different role at a different moment: a
-- capability token is minted by the dispatcher for somebody with no session, a
-- delegation is minted by the application from inside a live one, and that is
-- exactly the difference the mint policy below encodes.

-- +goose StatementBegin
create table public.act_delegations (
  -- Generated by the caller rather than by the database, so minting needs no
  -- `returning` and therefore no select privilege on a table of credentials.
  id uuid primary key,

  org_id uuid not null references public.organisations(id) on delete cascade,

  -- The person the agent is acting for. Not a foreign key, matching every other
  -- user reference in this schema: identity is Zitadel's and the domain mirrors
  -- rather than owns it.
  user_id uuid not null,

  -- WHAT IS ACTING, and it is not decoration.
  --
  -- §26.3 asks the audit row to read "the Analyst, on behalf of Ada, at 14:02".
  -- This is the first half of that sentence, and it is carried on the
  -- delegation rather than sent per request for the same reason the user id is:
  -- a value the caller supplies per call is a value the caller can choose, and
  -- an agent that can name itself can name itself something else.
  --
  -- Constrained to a slug shape because it lands in an audit row a customer
  -- reads. Free text there would put whatever a caller sent in front of a
  -- person as though this system vouched for it.
  acting_agent text not null,
  constraint act_delegations_acting_agent_check
    check (acting_agent ~ '^[a-z][a-z0-9-]{1,63}$'),

  -- Hashed, never in the clear, for the same reason `invitations.token_hash`
  -- and `capability_tokens.token_hash` are: a database dump, a backup or a
  -- support engineer reading this row must not yield a working credential.
  token_hash text not null,
  constraint act_delegations_token_hash_key unique (token_hash),

  -- False for an agent run, whose tools are many calls under one delegation.
  -- True for §8's approve link, where redeeming twice is the thing to prevent.
  single_use boolean not null default false,
  redeemed_at timestamptz,

  -- REVOCABLE, AND EXPIRING, AND THE SECOND IS THE ONE THAT ALWAYS WORKS.
  --
  -- §26.3 says a delegation "expires with the run". It cannot literally, and
  -- the reason is worth writing down rather than discovering: `agent_runs`
  -- (00019) is written ONCE, when the run finishes, so there is no run row to
  -- point at while the run is happening. A foreign key would have to be added
  -- after the fact to a table that forbids updates.
  --
  -- So "expires with the run" is two mechanisms. The caller revokes on the way
  -- out, which is the fast path and is best effort: a crashed run revokes
  -- nothing. The ceiling below is what holds when that fails, and it is why the
  -- ceiling is a constraint rather than a default somebody can pass around.
  revoked_at timestamptz,

  expires_at timestamptz not null,
  created_at timestamptz not null default now(),

  -- An hour is not a guess at how long a run takes; it is the outer bound
  -- beyond which "short-lived" stops being true. A run measured in minutes
  -- asks for minutes, in Go. This binds the migrator too, which is the point:
  -- grants and policies do not constrain a role that bypasses RLS and owns the
  -- schema, and "no delegation is ever long-lived" is a claim this table makes
  -- to a customer rather than to its own application.
  constraint act_delegations_ttl
    check (expires_at > created_at and expires_at <= created_at + interval '1 hour')
);
-- +goose StatementEnd

-- The two reads this table gets: resolution by hash (the unique index above
-- serves it) and "what is outstanding for this person", which is what a console
-- would show and what a revoke-all would sweep.
create index act_delegations_org_user_idx
  on public.act_delegations (org_id, user_id, created_at desc);

-- A delegation cannot be widened after it is minted.
--
-- Without this, the update grant that makes revocation possible would also make
-- "revoke" a way to push `expires_at` out, or to repoint `user_id` at somebody
-- else while keeping a credential that is already in an agent's hands. The
-- policy narrows who may update; this narrows what an update may be, and it
-- binds every role including the migrator, which is the same argument
-- `agent_runs_no_update` makes in 00019.
-- +goose StatementBegin
create function public.act_delegations_narrow_update() returns trigger
  language plpgsql
  as $$
begin
  if (new.id, new.org_id, new.user_id, new.acting_agent, new.token_hash,
      new.single_use, new.expires_at, new.created_at)
     is distinct from
     (old.id, old.org_id, old.user_id, old.acting_agent, old.token_hash,
      old.single_use, old.expires_at, old.created_at)
  then
    raise exception 'act_delegations: only revoked_at and redeemed_at may change on row %', old.id
      using errcode = 'check_violation';
  end if;

  -- Revocation and redemption are one-way. Clearing either would turn a
  -- credential somebody has already stopped into a working one again.
  if old.revoked_at is not null and new.revoked_at is null then
    raise exception 'act_delegations: row % is revoked and cannot be un-revoked', old.id
      using errcode = 'check_violation';
  end if;
  if old.redeemed_at is not null and new.redeemed_at is null then
    raise exception 'act_delegations: row % is redeemed and cannot be un-redeemed', old.id
      using errcode = 'check_violation';
  end if;

  return new;
end;
$$;
-- +goose StatementEnd

create trigger act_delegations_narrow_update
  before update on public.act_delegations
  for each row execute function public.act_delegations_narrow_update();

alter table public.act_delegations enable row level security;
alter table public.act_delegations force row level security;

------------------------------------------------------------------------------
-- Grants. THIS TABLE STARTS CLOSED (ENT-243).
------------------------------------------------------------------------------
-- 00002 set default privileges granting `kindlast_app` select, insert, update
-- and delete on every table the migrator creates, so this table arrives with
-- all four whatever is written below. Only an explicit revoke narrows it.
revoke all on public.act_delegations from kindlast_app;

-- Select, insert and update. NO DELETE: a delegation is revoked, not erased,
-- because what a customer was told an agent could do is evidence and evidence
-- that can be deleted is worth less than evidence that cannot.
grant select, insert, update on public.act_delegations to kindlast_app;

-- Nothing for `kindlast_agent`, `kindlast_ingest` or `kindlast_billing`. The
-- role that runs sweeps has no person to act for, and the two write-path roles
-- have no business near a credential that carries a human's authority.

-- MINTING: only for the person in the session, only in their organisation, and
-- only while they are a member of it.
--
-- The membership `exists` is the same clause every tenant policy carries, and
-- here it does a second job: an offboarded person cannot have a fresh
-- delegation minted for them even by a handler that still has their user id in
-- hand from earlier in the request.
create policy act_delegations_mint on public.act_delegations
  for insert to kindlast_app
  with check (
    org_id = (select current_setting('app.current_org_id')::uuid)
    and user_id = (select current_setting('app.current_user_id')::uuid)
    and exists (
      select 1 from public.memberships m
      where m.org_id = (select current_setting('app.current_org_id')::uuid)
        and m.user_id = (select current_setting('app.current_user_id')::uuid)
    )
  );

-- READING: your own, in the organisation you are acting in.
--
-- Not "everybody in the organisation": a delegation names one person's
-- authority, and an owner does not need to see which credentials exist for a
-- colleague in order to run the business. Revocation by somebody else is
-- ENT-230's follow-on if it is ever wanted, and it would be a deliberate
-- widening rather than an accident of this policy.
create policy act_delegations_select_own on public.act_delegations
  for select to kindlast_app
  using (
    org_id = (select current_setting('app.current_org_id')::uuid)
    and user_id = (select current_setting('app.current_user_id')::uuid)
    and exists (
      select 1 from public.memberships m
      where m.org_id = (select current_setting('app.current_org_id')::uuid)
        and m.user_id = (select current_setting('app.current_user_id')::uuid)
    )
  );

-- REVOKING: the same row set. The trigger above is what stops this being a way
-- to edit anything else.
create policy act_delegations_revoke on public.act_delegations
  for update to kindlast_app
  using (
    org_id = (select current_setting('app.current_org_id')::uuid)
    and user_id = (select current_setting('app.current_user_id')::uuid)
  )
  with check (
    org_id = (select current_setting('app.current_org_id')::uuid)
    and user_id = (select current_setting('app.current_user_id')::uuid)
  );

------------------------------------------------------------------------------
-- Resolution, for a caller who has no session yet
------------------------------------------------------------------------------
-- SECURITY DEFINER because the GUCs the policies read are not set: deciding
-- what to set them to is what this call is for. See the header.
--
-- ONE ANSWER FOR EVERY UNUSABLE DELEGATION. Expired, revoked, already redeemed
-- and never existed all return zero rows. Distinguishing them turns this into
-- an oracle for which credentials are real, and the caller has proved nothing
-- that entitles them to the difference. Same decision as `accept_invitation`
-- (00003) and `redeem_capability_token` (00015).
-- +goose StatementBegin
create function public.resolve_act_delegation(p_token_hash text)
returns table (user_id uuid, org_id uuid, acting_agent text)
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v public.act_delegations%rowtype;
begin
  select * into v
  from public.act_delegations d
  where d.token_hash = p_token_hash
    and d.revoked_at is null
    and d.expires_at > now()
  for update;

  if not found then
    return;
  end if;

  if v.single_use then
    if v.redeemed_at is not null then
      return;
    end if;
    -- Marked in the same statement that acts on it, under the row lock taken
    -- above, so two redemptions racing cannot both win.
    update public.act_delegations d
       set redeemed_at = now()
     where d.id = v.id;
  end if;

  user_id := v.user_id;
  org_id := v.org_id;
  acting_agent := v.acting_agent;
  return next;
end;
$function$;
-- +goose StatementEnd

revoke all on function public.resolve_act_delegation(text) from public;
grant execute on function public.resolve_act_delegation(text) to kindlast_app;

------------------------------------------------------------------------------
-- The audit row names the agent as well as the person
------------------------------------------------------------------------------
-- §26.3's sentence has two halves and the schema only had one. `audit_log`
-- already records `user_id` (who) and `actor_role` (what authority they held);
-- this is what was acting on their behalf, and NULL is the ordinary case of a
-- person doing something themselves. A column that was never null would say
-- nothing.
--
-- WHY A DEFAULT AND NOT A PARAMETER ON record_audit_log
--
-- Every audit row today goes through `record_audit_log`, so widening its
-- signature would work. A default binds more: it also catches a writer that
-- inserts directly, including one written years from now by somebody who never
-- read this migration. Given that this table's claim is "nobody, including us,
-- can revise this", the mechanism that cannot be forgotten is the right one.
--
-- The GUC is transaction-local, set by the delegated request's transaction
-- alongside the two tenancy GUCs, and cleared by nothing because `set_config`
-- with `is_local` true ends at commit. It is NOT a third tenancy GUC: no policy
-- reads it, and nothing decides anything from it. It labels a row. That is the
-- distinction ENT-225 drew when it removed `app.billing_enabled`, which was a
-- deployment fact a Go check should have owned; who is acting is neither a
-- deployment fact nor a decision, and a trigger deep inside an UPDATE has no
-- other way to learn it.
alter table public.audit_log
  add column acting_agent text
  default nullif(current_setting('app.acting_agent', true), '');

-- +goose Down
alter table public.audit_log drop column if exists acting_agent;

drop function if exists public.resolve_act_delegation(text);

drop policy if exists act_delegations_revoke on public.act_delegations;
drop policy if exists act_delegations_select_own on public.act_delegations;
drop policy if exists act_delegations_mint on public.act_delegations;
revoke all on public.act_delegations from kindlast_app;

drop table if exists public.act_delegations;
-- After the table, because dropping it takes the trigger with it and the
-- function would otherwise be dropped out from under a live trigger.
drop function if exists public.act_delegations_narrow_update();
