package records

import (
	"fmt"
	"strings"

	"github.com/Entear-OU/kindlast/apps/core-api/internal/domain/memory"
)

// The deterministic draft (ENT-287): the record an approval will create,
// filled from what the organisation has already told us, before anybody
// decides.
//
// # THE PROBLEM THIS EXISTS FOR
//
// Approving a `create_ropa` finding creates a `processing_activities` row from
// `findings.metadata.payload` (00036, `store/postgres/executor.go`). Measured
// on a real organisation, that payload was null, so approving produced a row
// named after the finding with every other column empty. A row, not a ROPA.
//
// ENT-261 built the path that fills it: the Hands prepares a plan, a person
// reads it, and the payload is what the Executor then creates the record from.
// What ENT-287 measured is that the path only runs when somebody presses a
// button. A finding nobody explains carries nothing, and the person who
// approves it gets the empty row.
//
// # WHY THIS ONE IS NOT A MODEL, WHEN THE HANDS IS
//
// Three reasons, and none of them is that a model would do it badly.
//
// A model call cannot happen where this happens. The draft has to be on the
// finding before a person opens it, which means inside the sweep, and
// `narrative.go` settled long ago what a model call inside the sweep
// transaction costs: minutes per finding with the act path blocked behind its
// locks, and everything lost on a timeout. Narration is a step AFTER the sweep
// precisely because of that, and a narrative can arrive late where a payload
// cannot.
//
// A drafted value has to name the fact it came from anyway. `from_fact` is
// required and `ValidatePrepared` refuses a value without one, so the only
// values anything may write are restatements of facts the organisation typed.
// For three of the ROPA register's six columns that restatement is exact, and
// a model adds nothing to "your data categories are the data categories you
// told us about" except cost, latency and a chance of paraphrase.
//
// And the columns a mapping cannot reach are exactly where the Hands earns its
// run. `purpose` and `retention_period` are not any fact restated; they are
// something a person knows and has never been asked. So this drafter fills
// what is mechanical and LEAVES the rest, with a reason, which is the same
// contract the Hands works to and the same thing a person reads.
//
// # WHAT MAKES A MAPPING HONEST
//
// One rule: the column must be the fact, not an inference from it. Every
// mapping below restates one recorded answer in the column that asks the same
// question, and a person reading the plan sees the fact key beside the value
// and can disagree with us. Nothing here reasons from an organisation's
// industry, its size or its sector to a value it never gave, because that is
// the plausible-looking compliance record this product exists not to produce.

// DraftSource is what `approval_plan.source` says about a plan drafted here.
//
// The Hands writes `hands` on its own plans. The two are told apart because a
// customer's trust in "a model wrote this" and "your own onboarding answers
// wrote this" is not the same and should not be presented as if it were.
const DraftSource = "profile_facts"

// Fact is one thing the organisation has told us, decoded.
//
// Values rather than the stored JSON, because the domain layer does not read
// the database's spelling of anything: the store decodes `org_profile_facts`
// the same way it decodes a payload, and hands the result over. A text fact is
// one value, a list fact is several, and a fact with none is a fact that was
// recorded and then emptied, which fills nothing.
type Fact struct {
	Key    string
	Values []string
}

// Draft is a proposed record: what could be filled, and what could not.
//
// The same two halves the Hands returns, and deliberately the same types, so
// one reader serves both plans and a surface never has to ask which produced
// the one it is rendering.
type Draft struct {
	Fields     []PreparedField
	LeftForYou []LeftForYou
}

// Empty reports a draft that proposes nothing, which is the ordinary outcome
// for a register with no mapping and for an organisation that has recorded
// nothing.
func (d Draft) Empty() bool { return len(d.Fields) == 0 }

// Explanation is the sentence a person reads above the decision.
//
// Authored here rather than generated by anything, for the reason
// `Register.Label` is authored: it is a statement about what this product will
// do if they press the button, and the deterministic path has no model to ask.
// It says which register gains an entry, how much of it came from their own
// answers, and how much is still theirs, which is the same three things the
// Hands' prompt asks a model for.
//
// It never says the entry is complete, because it never is: `name`, `purpose`
// and `retention_period` are nobody's but the customer's.
func (d Draft) Explanation(register Register) string {
	label := register.Label
	if label == "" {
		label = "the register"
	}
	return fmt.Sprintf(
		"Approving this adds one entry to %s. %s filled from what you have "+
			"already told us about your organisation, and %s left for you.",
		label,
		countOf(len(d.Fields), "column is", "columns are"),
		countOf(len(d.LeftForYou), "column is", "columns are"))
}

// countOf renders "1 column is" or "3 columns are", so the sentence above
// reads as English at either count.
func countOf(n int, one, many string) string {
	if n == 1 {
		return "1 " + one
	}
	return fmt.Sprintf("%d %s", n, many)
}

// mapping is one column that restates one fact.
type mapping struct {
	// The register column, which is the Executor's payload key.
	Field string
	// The fact whose value it restates.
	Fact string
	// Why the column is a person's when the fact is missing. Second person,
	// about this organisation, because "this field is required" tells somebody
	// nothing they did not already know from the empty box.
	WhenMissing string
}

// mappings is the whole vocabulary, keyed by register.
//
// Two registers are deliberately absent rather than present and empty, and
// which is which matters:
//
//	ai_systems  A vendor is not a system and a risk classification is a legal
//	            judgement under Annex III, which `registers.go` already refuses
//	            to let anything guess. There is no fact that IS an AI system
//	            entry, so there is no honest mapping to write.
//	dsars       A data-subject request arrives from a person. Its requester,
//	            its type and above all its receipt date are facts about an
//	            event, not about an organisation, and 00010 refuses to guess
//	            the last one because the Article 12(3) clock runs from it.
var mappings = map[string][]mapping{
	RegisterProcessingActivities: {
		{
			Field: "data_categories",
			Fact:  memory.KeyDataCategories,
			WhenMissing: "you have not told us which kinds of personal data you hold, " +
				"so this is yours to list",
		},
		{
			// `vendor_list` is recorded as "who else handles the
			// organisation's data" (domain/memory), which is what Article
			// 30(1)(d) asks for under the name recipients. A vendor that
			// handles the data is a recipient of it; one that does not was
			// recorded here by mistake, and the plan naming the fact is what
			// lets a person see that and say so.
			Field: "recipients",
			Fact:  memory.KeyVendorList,
			WhenMissing: "you have not told us who outside the organisation handles " +
				"this data, so this is yours to list",
		},
		{
			// Single-valued, and the fact is a list of every basis the
			// organisation relies on. See draftField: exactly one is a
			// restatement, several is a choice about which activity this
			// entry describes, and that choice is the person's.
			Field: "legal_basis",
			Fact:  memory.KeyLawfulBases,
			WhenMissing: "you have not told us which Article 6(1) basis you rely on, " +
				"so this is yours to name",
		},
	},
}

// unmapped is what a column with no fact behind it says for itself.
//
// Written per column rather than generated from the label, because these are
// the sentences a person reads under "what is still yours to do" and a
// generated one reads like a form validator. A column that gains no entry here
// falls back to `defaultReason`, which is honest and duller.
var unmapped = map[string]string{
	"name": "you have not told us what this activity is called, so the entry needs " +
		"a name a colleague would recognise",
	"purpose": "you have not told us why you process this data, and the purpose is " +
		"the part of an Article 30 entry only you can write",
	"retention_period": "you have not told us how long you keep it, or what decides " +
		"when it goes",
	"vendor": "you have not told us who supplies this system",
	"documentation_status": "you have not told us how far its technical documentation " +
		"has got",
	"risk_classification": "its classification under the AI Act is a legal judgement " +
		"about this system, so it is yours to make rather than ours to guess",
	"requester":    "a data-subject request comes from a person, and nobody has said who",
	"request_type": "nobody has said which right is being exercised",
	"handler":      "you have not told us who is dealing with this",
	"received_at": "the Article 12(3) deadline runs from the day the request arrived, " +
		"so that date is yours to give and never ours to infer",
}

// DraftFromFacts proposes the record an approval of this finding would create.
//
// Total over the register: every column comes back either filled, with the
// fact behind it, or left, with a reason. A plan that is silent about a column
// reads as a plan that finished it, which is the Hands' sixth rule and is a
// property here rather than an instruction.
//
// It never fails. A fact it does not recognise, a value it cannot use and a
// register it has no mapping for all produce the same thing: a column left for
// a person. There is no state of the world in which this refuses to answer,
// because the caller is a sweep that must not be failed by an organisation
// having answered its questions oddly.
func DraftFromFacts(register Register, facts []Fact) Draft {
	byKey := make(map[string]Fact, len(facts))
	for _, f := range facts {
		byKey[f.Key] = f
	}

	byField := make(map[string]mapping, len(mappings[register.Name]))
	for _, m := range mappings[register.Name] {
		byField[m.Field] = m
	}

	var draft Draft
	for _, field := range register.Fields {
		m, mapped := byField[field.Name]
		if !mapped {
			draft.LeftForYou = append(draft.LeftForYou, LeftForYou{
				Name: field.Name, Why: reasonFor(field),
			})
			continue
		}

		prepared, why := draftField(field, m, byKey[m.Fact])
		if why != "" {
			draft.LeftForYou = append(draft.LeftForYou, LeftForYou{Name: field.Name, Why: why})
			continue
		}
		draft.Fields = append(draft.Fields, prepared)
	}
	return draft
}

// draftField fills one column from one fact, or says why it could not.
//
// The two refusals are different and both are the person's to resolve. A fact
// with nothing in it means they have not answered. Several values in a column
// that holds one means they have answered about the organisation and the
// column asks about this activity: `ValidatePrepared` would refuse the plan
// outright for that (ErrTooManyValues, "a list would invent a spelling nobody
// chose"), so drafting it would produce a plan the validator throws away, and
// with it the columns that were fine.
func draftField(field Field, m mapping, recorded Fact) (PreparedField, string) {
	values := make([]string, 0, len(recorded.Values))
	for _, v := range recorded.Values {
		if strings.TrimSpace(v) != "" {
			values = append(values, v)
		}
	}
	if len(values) == 0 {
		return PreparedField{}, m.WhenMissing
	}
	if !field.ListValued && len(values) > 1 {
		return PreparedField{}, fmt.Sprintf(
			"you have recorded more than one (%s), and this column names the one "+
				"this entry relies on, which is yours to pick",
			strings.Join(values, ", "))
	}
	return PreparedField{Name: field.Name, Values: values, FromFact: m.Fact}, ""
}

// reasonFor is what an unmapped column says for itself.
func reasonFor(field Field) string {
	if why, written := unmapped[field.Name]; written {
		return why
	}
	return defaultReason(field)
}

// defaultReason is the fallback for a column nobody has written a sentence
// for: honest, and duller than one somebody wrote.
func defaultReason(field Field) string {
	return fmt.Sprintf(
		"you have not recorded anything that says %s, so this is yours to fill",
		strings.ToLower(field.Label))
}
