apiVersion: v1
kind: Namespace
metadata:
  name: kindlast-app
  labels:
    app.kubernetes.io/part-of: kindlast
---
apiVersion: v1
kind: Namespace
metadata:
  name: kindlast-data
  labels:
    app.kubernetes.io/part-of: kindlast
---
apiVersion: v1
kind: Namespace
metadata:
  name: kindlast-ingestion
  labels:
    app.kubernetes.io/part-of: kindlast
---
apiVersion: v1
kind: Namespace
metadata:
  name: kindlast-observability
  labels:
    app.kubernetes.io/part-of: kindlast
