package postgres

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"

	"github.com/Entear-OU/kindlast/apps/core-api/internal/domain/modelchoice"
)

// Where an organisation's model runs, on the request's transaction (ENT-236).
//
// # NO ORG PREDICATE ANYWHERE IN THIS FILE
//
// Every query runs with both tenancy GUCs set and 00031's policies supply
// `org_id = current_setting(...)` plus a membership check. A `where org_id = $1`
// here would be a second, weaker copy of a check the database already makes,
// and the day the two disagree it is the weaker one somebody trusts. Same rule
// `integrations.go` and `memory.go` follow.
//
// # EVERY CHANGE IS A REVOKE AND AN INSERT
//
// `kindlast_app` holds update on the status, revocation and credential columns
// and on nothing else, so there is no way to write this table that repoints an
// existing choice. That is not a limitation being worked around below: it is
// what makes the sequence of rows the history of where a customer's compliance
// data has been processed, and the two writers here are shaped to it.

// Choice is one organisation's active model configuration, without the secret.
type Choice struct {
	ID        string
	Provider  string
	BaseURL   string
	Model     string
	LastFour  string
	ChangedAt time.Time
	ChangedBy string
}

// Sealed is the credential as it sits in the column.
type Sealed struct {
	Ciphertext []byte
	KeyID      string
}

// ErrNoModelChoice is returned when an organisation is on the bundled model.
//
// A sentinel rather than a zero value with a boolean, because every caller has
// to handle it and an error is the shape Go makes hard to ignore. Being on the
// bundled model is not an error condition; it is the default, and the callers
// say so where they handle this.
var ErrNoModelChoice = errors.New("this organisation uses the model this deployment runs")

// ActiveModelChoice reads the choice the console shows.
//
// The credential columns are deliberately absent from the select. Nothing on
// the console surface needs the ciphertext, and a query that did not ask for it
// cannot leak it through a log line, an error string or a struct somebody
// marshals later.
func (t *Tenant) ActiveModelChoice(ctx context.Context) (Choice, error) {
	var choice Choice
	err := t.tx.QueryRow(ctx, `
		select id::text,
		       provider,
		       base_url,
		       model,
		       coalesce(credential_last_four, ''),
		       created_at,
		       coalesce(created_by::text, '')
		  from public.org_model_config
		 where status = 'active'`).Scan(
		&choice.ID, &choice.Provider, &choice.BaseURL, &choice.Model,
		&choice.LastFour, &choice.ChangedAt, &choice.ChangedBy)
	if errors.Is(err, pgx.ErrNoRows) {
		return Choice{}, ErrNoModelChoice
	}
	if err != nil {
		return Choice{}, fmt.Errorf("postgres: reading the model choice: %w", err)
	}
	return choice, nil
}

// UseHostedModel revokes whatever was active and records a new choice.
//
// The id is generated by the caller rather than by the column default, because
// the credential is sealed with the row id bound in as additional authenticated
// data (see internal/secrets) and the seal therefore has to happen before the
// insert. Same arrangement `CreateConnection` uses for the same reason.
//
// Returns the audit entry so the handler can hand it back. `actionType` is
// decided by the caller from what was there before, because "enabled",
// "changed" and "rotated" are three different things to have happened and only
// the caller knows which of them this is.
func (t *Tenant) UseHostedModel(
	ctx context.Context,
	id, provider, baseURL, model, lastFour string,
	sealed Sealed,
	actionType string,
) (Choice, string, error) {
	rowID, err := uuid.Parse(id)
	if err != nil {
		return Choice{}, "", fmt.Errorf("postgres: %q is not a uuid", id)
	}

	before, err := t.revokeActiveModelChoice(ctx)
	if err != nil {
		return Choice{}, "", err
	}

	var ciphertext []byte
	var keyID, hint *string
	if len(sealed.Ciphertext) > 0 {
		ciphertext = sealed.Ciphertext
		keyID = &sealed.KeyID
		if lastFour != "" {
			hint = &lastFour
		}
	}

	var choice Choice
	err = t.tx.QueryRow(ctx, `
		insert into public.org_model_config
		  (id, org_id, provider, base_url, model,
		   credential_ciphertext, credential_key_id, credential_last_four,
		   created_by)
		values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
		returning id::text, provider, base_url, model,
		          coalesce(credential_last_four, ''), created_at,
		          coalesce(created_by::text, '')`,
		rowID, t.orgID, provider, baseURL, model,
		ciphertext, keyID, hint, t.userID).Scan(
		&choice.ID, &choice.Provider, &choice.BaseURL, &choice.Model,
		&choice.LastFour, &choice.ChangedAt, &choice.ChangedBy)
	if err != nil {
		return Choice{}, "", fmt.Errorf("postgres: recording the model choice: %w", err)
	}

	entryID, err := t.recordModelAudit(ctx, actionType, &rowID, before, snapshotOf(&choice))
	if err != nil {
		return Choice{}, "", err
	}
	return choice, entryID, nil
}

// UseBundledModel revokes the active choice and records the reversal.
//
// Returns ErrNoModelChoice when there was nothing to revoke. Reverting an
// organisation that is already on the bundled model is not an event, and
// writing an audit row for it would put a decision nobody made into a
// regulatory record.
func (t *Tenant) UseBundledModel(ctx context.Context) (string, error) {
	before, err := t.revokeActiveModelChoice(ctx)
	if err != nil {
		return "", err
	}
	if before == nil {
		return "", ErrNoModelChoice
	}

	// `target_id` is the row that was revoked, so the entry points at the
	// configuration that stopped applying rather than at nothing.
	revoked, err := uuid.Parse(snapshotID(before))
	if err != nil {
		return "", fmt.Errorf("postgres: the revoked model choice has no id: %w", err)
	}
	return t.recordModelAudit(ctx, modelchoice.ActionReverted, &revoked, before, nil)
}

// revokeActiveModelChoice ends the current choice and returns what it was.
//
// Nil when there was none. The credential columns are nulled in the same
// statement, which the `org_model_config_revoked_holds_no_credential`
// constraint requires: a revoked row holding a sealed key would be a credential
// at rest in a system that has been told to stop using it.
func (t *Tenant) revokeActiveModelChoice(ctx context.Context) ([]byte, error) {
	var (
		id       string
		provider string
		baseURL  string
		model    string
		lastFour string
		since    time.Time
	)
	err := t.tx.QueryRow(ctx, `
		update public.org_model_config
		   set status = 'revoked',
		       revoked_at = now(),
		       revoked_by = $1,
		       credential_ciphertext = null,
		       credential_key_id = null
		 where status = 'active'
		returning id::text, provider, base_url, model,
		          coalesce(credential_last_four, ''), created_at`,
		t.userID).Scan(&id, &provider, &baseURL, &model, &lastFour, &since)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("postgres: revoking the model choice: %w", err)
	}

	return snapshotOf(&Choice{
		ID: id, Provider: provider, BaseURL: baseURL, Model: model,
		LastFour: lastFour, ChangedAt: since,
	}), nil
}

// modelSnapshot is what the audit row's `before` and `after` carry.
//
// NO CREDENTIAL, NOT EVEN THE CIPHERTEXT. `audit_log` is the table a customer
// exports and hands to somebody else, so anything in it is something they have
// published. The last four characters are here because they are what makes
// "the key was rotated" checkable, and they are not a secret.
type modelSnapshot struct {
	ID       string `json:"id"`
	Provider string `json:"provider"`
	BaseURL  string `json:"base_url"`
	Model    string `json:"model"`
	LastFour string `json:"credential_last_four,omitempty"`
	Since    string `json:"in_effect_since"`
}

func snapshotOf(choice *Choice) []byte {
	encoded, err := json.Marshal(modelSnapshot{
		ID:       choice.ID,
		Provider: choice.Provider,
		BaseURL:  choice.BaseURL,
		Model:    choice.Model,
		LastFour: choice.LastFour,
		Since:    choice.ChangedAt.UTC().Format(time.RFC3339),
	})
	if err != nil {
		// Unreachable: every field is a string. Returning nil rather than
		// panicking means a snapshot that somehow could not be built costs the
		// detail and not the decision.
		return nil
	}
	return encoded
}

// snapshotID pulls the id back out of a snapshot.
//
// Reading it from the JSON rather than threading a second return value through
// `revokeActiveModelChoice`, so there is one description of what was revoked
// and the audit row and the target id cannot disagree about it.
func snapshotID(snapshot []byte) string {
	var decoded modelSnapshot
	if err := json.Unmarshal(snapshot, &decoded); err != nil {
		return ""
	}
	return decoded.ID
}

// recordModelAudit writes the compliance event.
//
// Through `record_audit_log` rather than an insert, for the reason
// `findings.go` gives: the function snapshots the actor's role at the time of
// the action, and a second writer would be a second opinion about what a row
// means.
//
// The entry id is returned rather than discarded, which is the difference
// between a console that says "recorded" and one that can show the record.
func (t *Tenant) recordModelAudit(
	ctx context.Context,
	actionType string,
	target *uuid.UUID,
	before, after []byte,
) (string, error) {
	var entryID string
	err := t.tx.QueryRow(ctx, `
		select record_audit_log($1, $2, null, $3, $4, $5, $6, $7, $2)::text
	`, t.orgID, t.userID, actionType, "org_model_config", target, before, after).Scan(&entryID)
	if err != nil {
		return "", fmt.Errorf("postgres: recording the model decision: %w", err)
	}
	return entryID, nil
}

// ActiveModelChoiceForOrg resolves the endpoint one run should go to.
//
// On the producer pool, because that is where the narration job runs: it works
// for organisations nobody is signed in to, so there is no tenant transaction
// to hang this off. 00031 gives `kindlast_agent` a column-level select here and
// no write at all, and its argument for including the ciphertext is worth
// reading before this is copied anywhere else.
//
// Returns ErrNoModelChoice when the organisation is on the bundled model, which
// is the ordinary case and not a failure.
func (a *AgentStore) ActiveModelChoiceForOrg(ctx context.Context, orgID string) (Choice, Sealed, error) {
	org, err := uuid.Parse(orgID)
	if err != nil {
		return Choice{}, Sealed{}, fmt.Errorf("%w: %q is not a uuid", ErrBadOrganisation, orgID)
	}

	var (
		choice     Choice
		ciphertext []byte
		keyID      string
	)
	err = a.pool.QueryRow(ctx, `
		select id::text, provider, base_url, model,
		       credential_ciphertext, coalesce(credential_key_id, '')
		  from public.org_model_config
		 where org_id = $1 and status = 'active'`, org).Scan(
		&choice.ID, &choice.Provider, &choice.BaseURL, &choice.Model,
		&ciphertext, &keyID)
	if errors.Is(err, pgx.ErrNoRows) {
		return Choice{}, Sealed{}, ErrNoModelChoice
	}
	if err != nil {
		return Choice{}, Sealed{}, fmt.Errorf("postgres: resolving the model choice: %w", err)
	}

	// An org predicate IS written here, unlike everywhere else in this file,
	// and the difference is the pool. The agent's policy is unconditional
	// because it has no tenancy GUCs to be checked against (00008), so the
	// predicate is the tenancy rather than a duplicate of it.
	return choice, Sealed{Ciphertext: ciphertext, KeyID: keyID}, nil
}
