import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import {
  clientCredentials,
  resetClientCredentialsCache,
} from '@/lib/auth/client-credentials'

/**
 * Where the OAuth client's credentials come from (ENT-241).
 *
 * The console is a confidential client, so it holds a client secret. On the
 * bundled stack that secret is generated by Zitadel when the seed job creates
 * the application, which is after compose was written and therefore not a
 * value compose can carry. The seed writes it to a shared volume, and this is
 * the path from there into the process.
 *
 * It mirrors core-api's `internalClient`, deliberately: same precedence, same
 * JSON field names, same treatment of an unreadable file. Two mechanisms for
 * the same problem in one repository is one of them being wrong.
 */
describe('clientCredentials', () => {
  let dir: string
  const saved = { ...process.env }

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'kindlast-client-'))
    delete process.env.KINDLAST_OIDC_CLIENT_ID
    delete process.env.KINDLAST_OIDC_CLIENT_SECRET
    delete process.env.KINDLAST_OIDC_CLIENT_FILE
    resetClientCredentialsCache()
  })

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true })
    process.env = { ...saved }
    resetClientCredentialsCache()
  })

  it('reads the environment when it carries both halves', () => {
    process.env.KINDLAST_OIDC_CLIENT_ID = 'from-env'
    process.env.KINDLAST_OIDC_CLIENT_SECRET = 'secret-from-env'

    expect(clientCredentials()).toEqual({
      clientId: 'from-env',
      clientSecret: 'secret-from-env',
    })
  })

  it('reads the seed volume when the environment carries neither', () => {
    const path = join(dir, 'web-client.json')
    writeFileSync(
      path,
      JSON.stringify({ clientId: 'from-file', clientSecret: 'secret-in-file' }),
    )
    process.env.KINDLAST_OIDC_CLIENT_FILE = path

    expect(clientCredentials()).toEqual({
      clientId: 'from-file',
      clientSecret: 'secret-in-file',
    })
  })

  it('lets the environment win, so a real deployment never depends on a file', () => {
    const path = join(dir, 'web-client.json')
    writeFileSync(
      path,
      JSON.stringify({ clientId: 'from-file', clientSecret: 'secret-in-file' }),
    )
    process.env.KINDLAST_OIDC_CLIENT_FILE = path
    process.env.KINDLAST_OIDC_CLIENT_ID = 'from-env'
    process.env.KINDLAST_OIDC_CLIENT_SECRET = 'secret-from-env'

    expect(clientCredentials().clientId).toBe('from-env')
  })

  it('refuses rather than half-configuring when only the id is set', () => {
    process.env.KINDLAST_OIDC_CLIENT_ID = 'from-env'

    expect(() => clientCredentials()).toThrow(/KINDLAST_OIDC_CLIENT_SECRET/)
  })

  it('names the file in the error when the file cannot be read', () => {
    process.env.KINDLAST_OIDC_CLIENT_FILE = join(dir, 'absent.json')

    // The message has to say which file, because the likeliest cause is a
    // volume that was never mounted and the likeliest reader is somebody who
    // does not know a file is involved at all.
    expect(() => clientCredentials()).toThrow(/absent\.json/)
  })

  it('refuses a file that parses but carries no secret', () => {
    const path = join(dir, 'web-client.json')
    writeFileSync(path, JSON.stringify({ clientId: 'only-an-id' }))
    process.env.KINDLAST_OIDC_CLIENT_FILE = path

    expect(() => clientCredentials()).toThrow(/clientSecret/)
  })

  it('reads the file once, so sign-in does not stat a volume per request', () => {
    const path = join(dir, 'web-client.json')
    writeFileSync(
      path,
      JSON.stringify({ clientId: 'first', clientSecret: 'first-secret' }),
    )
    process.env.KINDLAST_OIDC_CLIENT_FILE = path

    expect(clientCredentials().clientId).toBe('first')

    writeFileSync(
      path,
      JSON.stringify({ clientId: 'second', clientSecret: 'second-secret' }),
    )
    expect(clientCredentials().clientId).toBe('first')

    // And a restart, which is the granularity configuration changes at.
    resetClientCredentialsCache()
    expect(clientCredentials().clientId).toBe('second')
  })
})
