package interceptor

import (
	"context"
	"errors"
	"fmt"
	"sort"

	"connectrpc.com/connect"
	"google.golang.org/protobuf/reflect/protoreflect"

	"github.com/Entear-OU/kindlast/libs/chassis/oidc"
	"github.com/Entear-OU/kindlast/libs/chassis/scope"
)

// ErrUndeclaredMethod is returned by NewScope when a registered RPC carries no
// required_scope option.
var ErrUndeclaredMethod = errors.New("interceptor: RPC declares no required scope")

// Scope enforces the per-RPC scope declared in the proto.
//
// The table is read from the method descriptors once, at construction, rather
// than maintained by hand in this file. That is the whole point of putting the
// option in the contract (§1.3): a hand-maintained map in middleware drifts
// within a month, because someone adds an RPC, forgets the map, and the method
// becomes reachable with any valid token, with nothing to notice.
type Scope struct {
	required map[string]string
	// humanClient is the OAuth client id whose tokens carry the human scope
	// set by construction. Empty disables client-class resolution entirely,
	// which is the behaviour every deployment had before ENT-221.
	humanClient string
}

// HumanScopes is what a person holds, and it is a constant rather than a grant.
//
// THE DECISION THIS ENCODES (ENT-221, approved 2026-08-16)
//
// Scopes bound what a CLIENT may do; memberships bound what a USER may do. For
// a first-party human client those two questions have different answers and
// only the second varies, so the human half of the scope layer carries no
// per-person information: every signed-in human gets the same set, and their
// actual authority in an organisation comes from memberships and RLS.
//
// Given that, asking an authorization server to store and grant a constant
// buys nothing and costs a failure mode. ENT-221 produced four separate bugs
// and every one had the same shape: a link that was configured somewhere,
// looked right, and silently carried nothing. A constant in this file cannot
// silently fail to be granted.
//
// # WHAT THIS IS NOT
//
// It is not a weakening of the scope layer. For machine clients the layer is
// unchanged and real: they hold granted roles, and `internal:*` is issued to
// them and never to a browser client. It stays a genuine consent boundary the
// day a third-party client asks for a narrowed grant, which is the only
// context where a per-client scope set carries information.
//
// It is also not an authority decision. Nothing here says a person may act in
// an organisation; that is a membership, checked by RLS on every row and by the
// handler for the rules RLS cannot express.
//
// Deliberately excludes every `internal:*` scope. A human client must never
// reach the platform surface, and the way that is guaranteed is by the set
// below not containing them rather than by a check somewhere that could be
// forgotten.
var HumanScopes = []string{
	"audit:read",
	"billing:manage",
	"billing:read",
	// The regulatory corpus (ENT-207). Every member reads it, including
	// viewers: the corpus is the same law for every customer and it is what a
	// finding's citation points at. A product whose users cannot look up the
	// obligation they are being told about is asking for trust it has not
	// earned.
	"corpus:read",
	"dashboard:read",
	"findings:act",
	"findings:read",
	// Connecting a customer's own systems (ENT-231). Both halves are human
	// scopes, and the write one deliberately so: deciding which of your own
	// tools a product may reach is the customer exercising control rather than
	// a privileged operation. What bounds it is membership, RLS and the
	// per-connection allow-list, none of which a scope could express.
	"integrations:read",
	"integrations:write",
	// What Kindlast knows about the organisation (ENT-228). Both halves are
	// human scopes, and the write one deliberately so: correcting a fact about
	// yourself is the customer exercising rectification, which is the thing
	// this product exists to make possible rather than a privileged operation.
	"memory:read",
	"memory:write",
	"notifications:read",
	"notifications:write",
	// The first conversation (ENT-212). The read is separate from the write
	// because every authenticated route asks where a person has got to before
	// deciding whether to route them into onboarding, and making that question
	// require the write scope would grant a scope for asking rather than for
	// acting.
	"onboarding:read",
	"onboarding:write",
	"org:manage",
	"org:read",
	"records:ai-systems:write",
	"records:dsar:write",
	"records:read",
	"records:ropa:write",
}

// WithHumanClient names the OAuth client whose tokens carry HumanScopes.
//
// The id is generated by the authorization server, so it reaches core-api as
// configuration rather than as a literal, the same way the audience and the
// roles claim name do. A literal here would be the third instance of the bug
// ENT-221 kept finding.
func WithHumanClient(clientID string) func(*Scope) {
	return func(s *Scope) { s.humanClient = clientID }
}

// NewScope builds the table and refuses to build it at all if any RPC is
// unannotated.
//
// Failing here means the binary does not start, which is the strongest
// available form of "fails closed": an unguarded RPC cannot be reached because
// the process serving it never came up. The runtime check in the interceptor
// is the second line, for a procedure that somehow reaches the chain without
// being in the table.
func NewScope(services []protoreflect.ServiceDescriptor, options ...func(*Scope)) (*Scope, error) {
	required := make(map[string]string)
	var undeclared []string

	for _, service := range services {
		scopes, missing := scope.OfService(service)
		undeclared = append(undeclared, missing...)

		for fullName, declared := range scopes {
			required[procedureFor(fullName)] = declared
		}
	}

	if len(undeclared) > 0 {
		sort.Strings(undeclared)
		return nil, fmt.Errorf("%w: %v", ErrUndeclaredMethod, undeclared)
	}

	scope := &Scope{required: required}
	for _, apply := range options {
		apply(scope)
	}
	return scope, nil
}

// holds reports whether a caller may exercise a scope.
//
// This is where client-class resolution happens, and it is two branches into
// the same answer. A token from the configured human client holds HumanScopes;
// so does a machine principal that has presented a delegation, because acting
// for a person means holding what a person holds and nothing else. Every other
// token holds exactly what it carries.
//
// The human set REPLACES the token's scopes rather than being unioned with
// them, which is the property that makes it a constant. A union would let a
// role granted to one person out of band widen what that person can do, and
// then the human half is no longer the same for everyone and no longer
// reasoned about as a class.
//
// REPLACEMENT IS ALSO WHAT MAKES A DELEGATION SAFE (ENT-230). The machine
// presenting one holds `internal:act-on-behalf` and may hold other `internal:*`
// scopes besides. Under a union, an agent acting for a viewer would carry the
// viewer's authority PLUS the platform surface, which is a strictly larger set
// than either party has: the person cannot reach `internal:ingest` and the
// machine cannot reach a tenant's rows, and the union hands the request both.
// HumanScopes deliberately contains no `internal:*` entry, so replacement is
// what closes that.
//
// `openid` survives the replacement because it is asserted by verification
// rather than granted (§1.3): it means signed in, not permitted, and the
// bootstrap calls that declare it must stay reachable.
//
// An empty ClientID never matches, even against an empty humanClient, because
// the comparison is guarded on humanClient being set. A provider that omits
// `client_id` therefore degrades to granted scopes rather than silently
// receiving the human set.
func (s *Scope) holds(claims *oidc.Claims, delegated bool, want string) bool {
	if delegated {
		return human(want)
	}
	if s.humanClient != "" && claims.ClientID == s.humanClient {
		return human(want)
	}
	return claims.HasScope(want)
}

// human reports whether the constant set covers a scope.
func human(want string) bool {
	if want == oidc.ScopeOpenID {
		return true
	}
	for _, held := range HumanScopes {
		if held == want {
			return true
		}
	}
	return false
}

// Interceptor checks the token's scopes against the one the RPC declared.
func (s *Scope) Interceptor() connect.UnaryInterceptorFunc {
	return func(next connect.UnaryFunc) connect.UnaryFunc {
		return func(ctx context.Context, req connect.AnyRequest) (connect.AnyResponse, error) {
			claims, ok := ClaimsFrom(ctx)
			if !ok {
				// Reachable only by wiring this interceptor before Auth, which
				// is a programming error rather than a request the caller
				// controls. Refuse rather than assume anything about identity.
				return nil, connect.NewError(connect.CodeInternal,
					errors.New("scope interceptor ran before authentication"))
			}

			procedure := req.Spec().Procedure
			declared, known := s.required[procedure]
			if !known {
				// An RPC absent from the table is unguarded, and an unguarded
				// RPC must be unreachable rather than open. Note the code: this
				// is not "you may not", it is "this server cannot say what
				// would be required", and answering 403 for it would suggest a
				// permission the caller could go and acquire.
				return nil, connect.NewError(connect.CodePermissionDenied,
					fmt.Errorf("%s declares no required scope", procedure))
			}

			// A delegation, if one was presented and resolved, decides which
			// set the caller is measured against. The error message stays the
			// same either way: telling a caller that the refusal was about the
			// person they are acting for rather than about their own token
			// describes the delegation's contents to somebody who has just
			// been refused.
			_, delegated := GrantFrom(ctx)

			if !s.holds(claims, delegated, declared) {
				return nil, connect.NewError(connect.CodePermissionDenied,
					fmt.Errorf("token does not carry the %q scope", declared))
			}

			return next(ctx, req)
		}
	}
}

// RequiredScope exposes the table for tests and for diagnostics.
func (s *Scope) RequiredScope(procedure string) (string, bool) {
	declared, ok := s.required[procedure]
	return declared, ok
}

// procedureFor converts a proto full method name into the Connect procedure
// path that arrives on the request.
//
// `kindlast.core.v1.SessionService.GetCurrentUser` becomes
// `/kindlast.core.v1.SessionService/GetCurrentUser`: the last dot becomes the
// slash separating service from method.
func procedureFor(fullName string) string {
	for i := len(fullName) - 1; i >= 0; i-- {
		if fullName[i] == '.' {
			return "/" + fullName[:i] + "/" + fullName[i+1:]
		}
	}
	return "/" + fullName
}
