#!/usr/bin/env bash
#
# Write apps/web/.env.local from the running stack, for a DEVELOPMENT SERVER.
#
# Since ENT-241 the stack serves the console itself, in a container behind the
# edge, and that console needs none of this: compose hands it
# KINDLAST_OIDC_CLIENT_FILE pointing at the same volume this script copies out
# of, so there is no host-side step between `up -d` and a working sign-in.
#
# This script is what `bun run dev` still needs, because a process on the host
# cannot read a docker volume. Nothing here has become redundant; what changed
# is that it is now one of two consoles rather than the only one, and it
# configures the one you run when you are changing the app.
#
# The web app is a confidential OAuth client, so it needs the client id and
# secret the seed job created in Zitadel. Those are written to a named docker
# volume rather than to the repository, which is correct (they are generated
# per environment, so they are not the sort of development default that belongs
# in git) and inconvenient in exactly one way: there is no host-side path to
# them. This script is that path.
#
# Run it after the stack is up and before starting the dev server:
#
#     docker compose -f deploy/compose.yaml up -d
#     ./scripts/web-env.sh
#     bun run dev
#
# Re-run it after `docker compose down -v`, which discards the volume and
# makes Zitadel issue a new client on the next boot. A stale .env.local is the
# likeliest reason sign-in starts failing with `invalid_client`.
set -euo pipefail

cd "$(dirname "$0")/.."

COMPOSE_FILE="deploy/compose.yaml"
TARGET="apps/web/.env.local"

# The stack this worktree owns (ENT-250). In a single checkout these are the
# documented defaults; in a worktree that ran scripts/stack-env.sh they are its
# own block, and `docker compose` below picks the same project up from
# deploy/.env without being told.
AUTH_PORT="${KINDLAST_AUTH_PORT:-8300}"
EDGE_PORT="${KINDLAST_EDGE_PORT:-8000}"
REDIS_PORT="${KINDLAST_REDIS_PORT:-6379}"

read_volume_file() {
  docker compose -f "$COMPOSE_FILE" run --rm --no-deps -T \
    --entrypoint sh seed -c "cat $1" 2>/dev/null
}

CLIENT_JSON="$(read_volume_file /machinekey/web-client.json)"
if [ -z "$CLIENT_JSON" ]; then
  echo "web-env: could not read web-client.json from the stack." >&2
  echo "         Is it up?  docker compose -f $COMPOSE_FILE up -d" >&2
  exit 1
fi

CLIENT_ID="$(printf '%s' "$CLIENT_JSON" | jq -r '.clientId')"
CLIENT_SECRET="$(printf '%s' "$CLIENT_JSON" | jq -r '.clientSecret')"

cat > "$TARGET" <<EOF
# Generated by scripts/web-env.sh from the running compose stack.
# Not committed: these credentials are issued per environment, and a new one
# is created every time the stack is torn down with \`down -v\`.

KINDLAST_OIDC_ISSUER=http://localhost:${AUTH_PORT}
KINDLAST_OIDC_CLIENT_ID=${CLIENT_ID}
KINDLAST_OIDC_CLIENT_SECRET=${CLIENT_SECRET}
KINDLAST_WEB_REDIRECT_URI=http://localhost:3000/auth/callback

# Through the edge, because core-api publishes no ports. Same door from the
# host as from another container, so there is no development-only shortcut.
KINDLAST_CORE_API_URL=http://localhost:${EDGE_PORT}

KINDLAST_REDIS_URL=redis://127.0.0.1:${REDIS_PORT}
EOF

echo "web-env: wrote $TARGET (client ${CLIENT_ID})"
