-- Seed the obligations catalogue (ENT-157)
--
-- Generated from data/corpus/obligations.json by
-- scripts/generate-obligations-seed.ts — DO NOT EDIT BY HAND. Re-run
-- `pnpm generate:obligations-seed` after editing the corpus; a drift-guard
-- unit test (__tests__/lib/corpus/obligations-seed-sql.test.ts) fails if this
-- file and the corpus disagree.
--
-- Why a migration and not the `pnpm ingest:obligations` script: nothing ever
-- ran that script automatically, so production shipped with an empty
-- `public.obligations` and the Watcher's gap detector iterated zero rows —
-- an empty feed for every real user (ENT-157). Seeding from a migration means
-- every environment (local reset, CI `supabase start`, remote deploy) gets
-- the catalogue with no manual step.
--
-- Idempotent: `on conflict (slug) do update` upserts by the natural key, so
-- re-applying the migration (or re-running the curated ingest) converges to
-- the same row state. Rows removed from a later corpus snapshot are left
-- in place — same non-destructive policy as the runtime ingest.

insert into public.obligations
  (slug, title, summary, citation_celex, citation_kind, citation_article, citation_recital, citation_annex, citation_paragraph, applies_when, severity, due_within_days, recurrence, effective_date, topic_tags)
values
  ('gdpr-art-30-ropa',
   'Records of Processing Activities (ROPA)',
   'Article 30 GDPR — Controllers (and processors) must maintain a written record of processing activities under their responsibility, including purposes, categories of data subjects and data, recipients, third-country transfers, retention schedules, and a general description of technical and organisational security measures. The 250-employee exemption in Article 30(5) is narrow — it does not apply where processing is not occasional, involves special categories, or is likely to result in a risk to data subjects — so most SMEs cannot rely on it.',
   '32016R0679',
   'article',
   30,
   null,
   null,
   null,
   '{"role":"controller","requires":["ropa"]}'::jsonb,
   'high',
   null,
   'continuous',
   '2018-05-25',
   array['ropa', 'documentation', 'accountability']::text[]),
  ('gdpr-art-35-dpia',
   'Data Protection Impact Assessment (DPIA) for high-risk processing',
   'Article 35 GDPR — Before processing that is likely to result in a high risk to the rights and freedoms of natural persons, the controller must carry out a Data Protection Impact Assessment. Triggers include systematic and extensive evaluation of personal aspects (including profiling) producing legal effects, large-scale processing of special categories or criminal-conviction data, and systematic monitoring of publicly accessible areas. National supervisory authorities publish DPIA blacklists under Art 35(4); consult yours.',
   '32016R0679',
   'article',
   35,
   null,
   null,
   null,
   '{"role":"controller","thresholds":{"high_risk":true}}'::jsonb,
   'high',
   null,
   'ad-hoc',
   '2018-05-25',
   array['dpia', 'risk', 'profiling']::text[]),
  ('gdpr-art-33-breach-notification',
   'Personal data breach notification to the supervisory authority (72 hours)',
   'Article 33 GDPR — The controller must notify the competent supervisory authority of a personal data breach without undue delay and, where feasible, no later than 72 hours after becoming aware of it. The 72-hour window starts at the moment of awareness, not at detection by an automated system. If the breach is unlikely to result in a risk to natural persons the notification can be skipped; the controller''s reasoning must still be documented under Art 33(5). Processors notify the controller without undue delay under Art 33(2).',
   '32016R0679',
   'article',
   33,
   null,
   null,
   null,
   '{"role":"controller"}'::jsonb,
   'high',
   0,
   'on-event',
   '2018-05-25',
   array['breach', 'notification', 'incident-response']::text[]),
  ('gdpr-art-34-breach-communication',
   'Communication of a personal data breach to the data subject',
   'Article 34 GDPR — When a personal data breach is likely to result in a high risk to the rights and freedoms of natural persons, the controller must communicate the breach to the affected data subjects without undue delay. Article 34(3) lists exceptions: appropriate prior protection (encryption), subsequent risk-mitigating measures, or disproportionate effort (in which case a public communication suffices). Independent of the Article 33 supervisory-authority notification — both can apply to the same incident.',
   '32016R0679',
   'article',
   34,
   null,
   null,
   null,
   '{"role":"controller","thresholds":{"high_risk":true}}'::jsonb,
   'high',
   null,
   'on-event',
   '2018-05-25',
   array['breach', 'data-subject', 'incident-response']::text[]),
  ('gdpr-art-37-dpo-appointment',
   'Designation of a Data Protection Officer (DPO)',
   'Article 37 GDPR — A controller or processor must designate a DPO where (a) processing is carried out by a public authority, (b) the core activities require regular and systematic monitoring of data subjects on a large scale, or (c) the core activities consist of large-scale processing of special categories or criminal-conviction data. Member State law may add further mandatory cases. Voluntary designations are permitted but trigger the full Article 38–39 duty stack — Article 39 lists the DPO''s tasks (advising, monitoring compliance, DPIA cooperation, supervisory-authority liaison).',
   '32016R0679',
   'article',
   37,
   null,
   null,
   null,
   '{"role":"controller","thresholds":{"large_scale_monitoring":true},"requires":["dpo"]}'::jsonb,
   'high',
   null,
   'continuous',
   '2018-05-25',
   array['dpo', 'governance', 'accountability']::text[]),
  ('gdpr-art-6-lawful-basis',
   'Lawful basis for processing personal data',
   'Article 6 GDPR — Processing personal data is lawful only if at least one of six bases applies: consent, contract necessity, legal obligation, vital interests, public task, or legitimate interests. The chosen basis must be identified before processing starts and surfaced in the Article 13/14 transparency notice. Switching basis mid-flight is generally disallowed (see EDPB Guidelines 5/2020 on consent §121). Public authorities cannot rely on legitimate interests for their core tasks (Art 6(1)(f) closing sentence).',
   '32016R0679',
   'article',
   6,
   null,
   null,
   null,
   '{"role":"controller"}'::jsonb,
   'high',
   null,
   'continuous',
   '2018-05-25',
   array['lawful-basis', 'consent', 'principles']::text[]),
  ('gdpr-art-7-consent-conditions',
   'Conditions for consent (where consent is the lawful basis)',
   'Article 7 GDPR — Where processing is based on consent, the controller must be able to demonstrate that consent was given (Art 7(1)). Consent must be a freely given, specific, informed, and unambiguous indication via a clear affirmative action (Art 4(11)). Withdrawal must be as easy as giving consent (Art 7(3)); pre-ticked boxes are invalid (Rec. 32). Consent is presumed not freely given where there is a clear imbalance between data subject and controller (employer/employee, public authority).',
   '32016R0679',
   'article',
   7,
   null,
   null,
   null,
   '{"role":"controller","lawful_basis_includes":"consent"}'::jsonb,
   'high',
   null,
   'continuous',
   '2018-05-25',
   array['consent', 'lawful-basis']::text[]),
  ('gdpr-arts-12-22-data-subject-rights',
   'Data subject rights (information, access, rectification, erasure, restriction, portability, objection)',
   'Articles 12–22 GDPR — Controllers must facilitate the exercise of data subject rights: transparent information under Articles 12–14, access under Article 15, rectification under Article 16, erasure ("right to be forgotten") under Article 17, restriction under Article 18, notification of recipients under Article 19, portability under Article 20, objection under Article 21, and safeguards against solely automated decisions under Article 22. Standard response window is one month (Art 12(3)), extendable by two months for complex requests. No fee for manifestly unfounded or excessive requests — a fee or refusal must be justified.',
   '32016R0679',
   'article',
   12,
   null,
   null,
   null,
   '{"role":"controller"}'::jsonb,
   'high',
   30,
   'on-event',
   '2018-05-25',
   array['data-subject-rights', 'dsar', 'transparency']::text[]),
  ('gdpr-art-32-security-of-processing',
   'Security of processing — technical and organisational measures',
   'Article 32 GDPR — Controllers and processors must implement appropriate technical and organisational measures (TOMs) to ensure a level of security appropriate to the risk, taking into account the state of the art, costs, and the nature/scope/context/purposes of processing. The non-exhaustive list in Art 32(1) names pseudonymisation, encryption, confidentiality/integrity/availability/resilience, the ability to restore access after an incident, and a process for regularly testing and evaluating effectiveness. Adherence to an approved Article 40 code of conduct or Article 42 certification can be evidence of compliance.',
   '32016R0679',
   'article',
   32,
   null,
   null,
   null,
   '{"role":"controller"}'::jsonb,
   'high',
   null,
   'continuous',
   '2018-05-25',
   array['security', 'toms', 'encryption']::text[]),
  ('gdpr-chapter-v-international-transfers',
   'International transfers to third countries — Chapter V safeguards',
   'Articles 44–49 GDPR — Personal data transfers to a country outside the EEA require either an adequacy decision (Art 45), appropriate safeguards (Art 46 — Standard Contractual Clauses, Binding Corporate Rules, approved codes/certifications), or a narrow Article 49 derogation. Schrems II (CJEU C-311/18) requires a Transfer Impact Assessment to evaluate whether the target country''s surveillance laws undermine SCC protections; supplementary measures may be needed. The EU-US Data Privacy Framework (July 2023 adequacy decision) covers certified US importers.',
   '32016R0679',
   'article',
   44,
   null,
   null,
   null,
   '{"role":"controller","thresholds":{"cross_border_transfers":true},"requires":["transfer_safeguards"]}'::jsonb,
   'high',
   null,
   'continuous',
   '2018-05-25',
   array['transfers', 'scc', 'third-country']::text[]),
  ('gdpr-art-28-processor-contracts',
   'Controller–processor contracts (Article 28 DPAs)',
   'Article 28 GDPR — Where a controller engages a processor, the processing must be governed by a written contract (the Data Processing Agreement) binding the processor to a defined list of duties: process only on documented instructions, ensure confidentiality, take Article 32 security measures, engage sub-processors only with prior controller authorisation, assist with data subject rights and breach handling, and delete or return data at the end of the engagement. The European Commission published SCC-style Article 28 template clauses in Decision 2021/915.',
   '32016R0679',
   'article',
   28,
   null,
   null,
   null,
   '{"role":"controller","engages_processor":true}'::jsonb,
   'high',
   null,
   'continuous',
   '2018-05-25',
   array['processor', 'contracts', 'vendor-management']::text[]),
  ('ai-act-art-4-ai-literacy',
   'AI literacy for staff who operate or are affected by AI systems',
   'Article 4 EU AI Act — Providers and deployers of AI systems must take measures to ensure, to their best extent, a sufficient level of AI literacy of their staff and other persons dealing with the operation and use of AI systems on their behalf. The measures must take into account the persons'' technical knowledge, experience, education, training, the context in which the AI systems are used, and the persons or groups of persons on which the AI systems will be used. In force since 2 February 2025 (one of the earliest AI Act provisions to apply).',
   '32024R1689',
   'article',
   4,
   null,
   null,
   null,
   '{"role":"deployer","requires":["ai_register"]}'::jsonb,
   'medium',
   null,
   'continuous',
   '2025-02-02',
   array['ai-act', 'ai-literacy', 'training']::text[]),
  ('ai-act-art-26-deployer-obligations',
   'Deployer obligations for high-risk AI systems',
   'Article 26 EU AI Act — Deployers of high-risk AI systems must use the system in accordance with the provider''s instructions for use, assign human oversight to natural persons with appropriate competence (Art 26(2)), monitor operation, keep automatically generated logs for at least six months (Art 26(6)), inform workers and their representatives before putting a high-risk system into service in the workplace (Art 26(7)), and conduct a fundamental rights impact assessment under Article 27 where applicable. Most Article 26 duties apply from 2 August 2026.',
   '32024R1689',
   'article',
   26,
   null,
   null,
   null,
   '{"role":"deployer","thresholds":{"high_risk":true}}'::jsonb,
   'high',
   null,
   'continuous',
   '2026-08-02',
   array['ai-act', 'high-risk', 'deployer']::text[]),
  ('ai-act-annex-iii-high-risk-systems',
   'High-risk system classification under Annex III',
   'Annex III EU AI Act — Standalone AI systems falling under one of eight enumerated use-case areas are designated high-risk under Article 6(2): biometrics, critical infrastructure, education and vocational training, employment and worker management, access to essential services, law enforcement, migration and border control, and administration of justice and democratic processes. High-risk classification triggers the full Articles 9–17 obligation stack (risk management, data governance, technical documentation, record-keeping, transparency, human oversight, accuracy/robustness/cybersecurity). Annex III obligations apply from 2 August 2026 (subject to any Digital Omnibus deferral).',
   '32024R1689',
   'annex',
   null,
   null,
   'III',
   null,
   '{"role":"provider","thresholds":{"high_risk":true}}'::jsonb,
   'high',
   null,
   'continuous',
   '2026-08-02',
   array['ai-act', 'high-risk', 'annex-iii']::text[]),
  ('ai-act-art-50-transparency',
   'Transparency obligations for certain AI systems (deepfakes, chatbots, emotion recognition)',
   'Article 50 EU AI Act — Providers of AI systems intended to interact directly with natural persons must design the system so that affected persons are informed they are interacting with an AI (chatbot disclosure). Deployers of emotion-recognition or biometric-categorisation systems must inform exposed persons. Deployers of generative AI producing image/audio/video content constituting deepfakes must disclose the artificial origin; text published on matters of public interest is similarly disclosable unless under editorial control. Article 50 duties apply from 2 August 2026.',
   '32024R1689',
   'article',
   50,
   null,
   null,
   null,
   '{"role":"deployer"}'::jsonb,
   'medium',
   null,
   'continuous',
   '2026-08-02',
   array['ai-act', 'transparency', 'deepfake']::text[])
on conflict (slug) do update set
  title = excluded.title,
  summary = excluded.summary,
  citation_celex = excluded.citation_celex,
  citation_kind = excluded.citation_kind,
  citation_article = excluded.citation_article,
  citation_recital = excluded.citation_recital,
  citation_annex = excluded.citation_annex,
  citation_paragraph = excluded.citation_paragraph,
  applies_when = excluded.applies_when,
  severity = excluded.severity,
  due_within_days = excluded.due_within_days,
  recurrence = excluded.recurrence,
  effective_date = excluded.effective_date,
  topic_tags = excluded.topic_tags;
